---
title: "Syllabus: Creating your own (quantitative) research project in R"
format:
  pdf:
    suppress-bibliography: true
---

Version: 2

You can find the latest version of the syllabus on the project [here](https://github.com/HeinerSalomon/Own_research_project_in_R).

## Introduction

This course wants to enable students to run their own (quantitative) research project in R. In the process, they will learn basic data wrangling and data visualisation in R. Every student will choose a project that they want to conduct using publicly available data of their choosing (some examples will be provided) and will, in consultation with the course coordinator, work towards a project report at the end of the course that they will present to the other students. Students will analyse their data in the open-source programme R and will be encouraged to write their final reports in it, too. The course will be a mixture of lectures on practical issues and a project based working sessions in exchange with the course coordinator and other students to make use of peer-to-peer learning. The lecture will be tailored to the needs and levels of the participating students.

In this course students are encouraged to run their own small-scale analysis project using R from beginning to end: choosing a topic and research question they find interesting, selecting and downloading the relevant data, using simple (presumably mostly) descriptive statistics such as means, and writing a report about their findings. They will be encouraged to use Quarto/ Rmarkdown, the integrated tool within R-Studio, to write their final reports and export them into PDF to automatically integrate updated findings. Also, students will be encouraged to upload and maintain their project on git. This course teaches practical skills and combines it with theoretical grounding in reproducible science. Hence it can be used as a good foundation for quantitative bachelor or master theses, and to learn skills that can be used also outside of academia.

## Assessment

Students can take the course for 3 CP or 6 CP. The final assessment will depend on the amount of CP students chose. **Both assessments** include

- the **simple progress report every two weeks** every second Friday before 15:00 on StudIP. It just about one paragraph in an unstructured form, including reasons for no progress, which will always happen, is no problem and part of the process. I expect five progress reports for the duration of the course. One of the five can be dropped without explanation, but after that need a really good excuse.

- the **final script** of the project. The final script should be executable from any machine as long as one has the data and R installed. Also, the script should include many comments, so that an external person can understand what it is that you have done.

Beyond that, the two different levels encompass the following two assessments:

3 Credit Points (CP):

-   Short presentation (10 minutes)

-   Short final research note with references (\~5 pages, at least one high-quality graph) by August 14 the latest

6 Credit Points (CP):

-   Long presentation (20 minutes)

-   Long final research note with references (\~10 pages, at least two high-quality graphs) by August 14 the latest

Grading happens in the following way:

The script, the presentation and the research note each contribute 33% to the final grade. The three assessments will be graded in turn in the following way:

### Assessment - Script (each 25%)

-   Correct: Is the script correct and does what it should?
-   Structure: Is the structure helpful and appropriate?
-   Clarity: Does it become clear what the script does and when?
- Comments: Are the comments in the script enough to follow it?

### Assessment - Presentation criteria (each 25%)

-   Structure: Is the structure helpful and appropriate?
-   Clarity: Does it become clear what you present on?
-   Visuals: Does the presentation look appealing?
-   Presentation: Are you presenting convincingly?

### Assessment - Research note criteria (each 25%)

-   Structure: Is the structure helpful and appropriate?
-   Clarity: Does it become clear what you are writing on?
-   Visuals: Does the data sicualisation look appealing?
-   References: Are the references correct and relevant?



## Prerequisites

-   Basic understanding of statistics (means, confidence intervals), for instance through Statistics 1 at Bremen University

-   Preferably but not necessarily some basic experience in R or alternative statistics software (Stata, Python, SAS etc.)

-   Laptop that students can bring to class, preferably pre-installed with R, R-studio and Quarto

## Time and Location

Time: Monday 14:00 - 16:00

Location: Socium, Mary-Somerville-Str. 3, Room 3.3390

## Course schedule (preliminary)

This is the preliminary course schedule. It may change based on student demand.

~~April 6th:~~ Easter

~~April 13th:~~ Course cancelled by me

April 20th: Course introduction & installing R and Rstudio, Quarto and Github

[April 27th]{.underline}: Choosing a research project

May 4th: Short introduction to Rstudio and Quarto

[May 11th]{.underline}: Reproducible science (and git)

May 18th: The tidyverse: What is it and how can you use it?

~~May 25th~~: Whit Monday

[June 1st]{.underline}: Good practices when coding

June 8th: Crash course in data wrangling

[June 15th]{.underline}: Introduction to data visualisation in ggplot

June 22nd: More data visualisation in ggplot

[June 29th]{.underline}: Presentations

July 6th: Final class

Notes:

The ~~struck through~~ lessons are missing due to holidays.

The [underlined]{.underline} lessons are weeks with progress reports due.

## Instructor

Heiner Salomon

heiner.salomon\@uni-bremen.de

Office: 5.4010 (floor above the seminar room)

Office days: Monday and Wednesday

## Inspiration:

-   Gentzkow, M. and Shapiro, JM. (2014): Code and Data for the Social Sciences: A Practitioner’s Guide <https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf>

-   Munafò, Marcus R., Brian A. Nosek, Dorothy V. M. Bishop, et al. ‘A Manifesto for Reproducible Science’. Nature Human Behaviour 1, no. 1 (2017): 0021. <https://doi.org/10.1038/s41562-016-0021>.

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund. ‘Introduction’. In R for Data Science, 2nd Edition, Second edition. O’Reilley, <https://r4ds.hadley.nz/intro.html>.
